### ISSUE TITLE
Initialization of azure media player leading to crash: "window.amp is not a function"

### ISSUE THREAD

**Issue by Moristotle** [SidKH/react-azure-mp#17]
Hi, 

First, thanks for this amazing library, makes it a breeze to work with Azure Media Service within React applications. 
We are currently building a platform that will be rendering mulltiple videos that is uploaded to and handled by Azure Media Services. Integrating and using the library within our application works out of the box, but sometimes when either refreshing the application and/or initializing the app, the following error is triggered ("window.amp is not a function): 

![image](https://user-images.githubusercontent.com/43928778/101230480-cbb3e400-36a5-11eb-8f44-f354d09380b9.png)

Any ideas as to what to do/how to handle this error? - When the error occurs, the media player just renders a black box + the whole application crashes. 

Considering that window.amp seems to be related to a function that is used by the library to initialize the player (under the good) and attached to the global window object, I attempted to add an evenListener to the window object and programatically trigger a refresh/reload of amp, but so far I have not been able to solve the issue.

**Comment by Moristotle** [comment]
update: calling loadLibrary (function exposed from the lib) within a useEffect hook (prior to rendering amp) seems to resolve the issue. - In this particular use case, I called the loadLibray at pageLevel (where the component containing amp is rendered). 

Just leaving this here in case someone experiences a similar issue! :)

Question besides the point: is it possible to use this library in a server-side rendered application? (particularly thinking about the implicit reference to/usage of the window object which is not available outside of the client).

**Comment by SidKH** [comment]
Hey @Moristotle.
Thanks for creating an issue. 
There was indeed a bug with `loadLibrary` and multiple instances of the component.
It's fixed in the latest release 1.0.3.
Please update the package instead of calling `loadLibrary` directly, since it may result in duplication of the library script on your page.

**Comment by SidKH** [comment]
Let's move server-side rendering discussion into a [separate issue](https://github.com/SidKH/react-azure-mp/issues/19)
