### ISSUE TITLE
SSR

### ISSUE THREAD

**Issue by SidKH** [SidKH/react-azure-mp#19]
@Moristotle

> Question besides the point: is it possible to use this library in a server-side rendered application? (particularly thinking about the implicit reference to/usage of the window object which is not available outside of the client).

**Comment by SidKH** [comment]
@Moristotle

I haven't tried using it with server-side rendering, but I don't see any direct obstacles to it. Both library initialization and usage of `window` attached method happening after `componentDidMount` and should work fine.

Do you mind trying it out?

**Comment by SidKH** [comment]
Just tested it with Next.js. Works fine.

**Comment by Moristotle** [comment]
This is great news!

I just upgraded to the latest version (1.0.3) and tested it within a Next.js application. I can verify that amp works under all of these conditions: 
1. Rendered at component-level.
2. Rendered in a client-side rendered page.
3. Rendered within a server-side rendered page
4. When dynamically imported (using next/dynamic).

This should cover most (if not all) use cases for azure media player (as far as I'm aware).

Would be nice to have this documented somewhere (as it is indeed a useful and remarkable feature of the library that it is able to function properly within all of the mentioned conditions)! 

Once again, thanks for creating this library and for taking your time to answer and assist us! :)
