### ISSUE TITLE
Integrating plugins

### ISSUE THREAD

**Issue by patrickjquinn** [SidKH/react-azure-mp#22]
Hi there, 

I'm looking use the plugin field in the options of the initialiser to integrate some analytics. Only problem is, the plugin interface should be predefined prior to being loaded into a player instance but it looks like neither the 'amp' nor 'window.amp' namespace are available until the player loads the library. 

In a normal JS use case you'd include the script tag for the library which would have it loaded before use but is there a mechanism to pre-load the Azure MP library prior to instantiation?

Cheers for your time.

**Comment by SidKH** [comment]
Hey, thanks for creating an issue!
  
Unfortunately, given the mechanics of Azure MP plugins, which modifies `window` object, there is not much that can be done to simplify this process, or preload plugins somehow. 
  
You can, however, add plugins using official guidance by adding scripts and links to the head.  
In this case, you also should add the assets for the media player library itself.

For example:
```html
<head>
  ...
  <link href="//amp.azure.net/libs/amp/latest/skins/amp-default/azuremediaplayer.min.css" rel="stylesheet">
  <script src= "//amp.azure.net/libs/amp/latest/azuremediaplayer.min.js"></script>
  <link href="assets/amp-zoom.css" rel="stylesheet">
  <script src="assets/amp-zoom.js"></script>
</head>
```

After that, you can use `AzureMP` component as usual.
  
Please use the latest version of `react-azure-mp` -  `1.0.4`.  
It detects whether azure-media-player script is preloaded in HTML, to prevent any duplications.

**Comment by patrickjquinn** [comment]
I was using dependency injection so I had to basically call loadLibrary when the component was rendered and fire off an event on completion to let the plugin know it could load but its working perfectly after that 👍
