### ISSUE TITLE
How can I setup "onplay" and "onprogress" functions here?

### ISSUE THREAD

**Issue by deanjohns** [SidKH/react-azure-mp#24]

**Comment by LTrain** [comment]
We just added event listeners on object creation. 

 return (<AzureMP
        id={videoObj.Url}
        onInstanceCreated={player => {
            player.addEventListener("ready", () => onAzureReady(player));
            player.addEventListener("play", () => playingCallback(player));
            player.addEventListener("timeupdate", () => timeUpdate(player));
            player.addEventListener("ended", () =>onEnded(player))
            //player.addEventListener("pause",() => pauseCallback(player));
        }}
        skin="amp-flush"
        options={{ controls: controls, autoplay: autoplay }}
        src={[{ src: videoObj.Url, type: streamingType }]}
    />
    );

**Comment by SidKH** [comment]
Sorry, I missed this one
@LTrain solution is right, you can do it in `onInstanceCreated`
