### ISSUE TITLE
Jumping to a point in time in the video

### ISSUE THREAD

**Issue by FluentSynergyDW** [SidKH/react-azure-mp#29]
Hi

Is it possible using react-azure-mp to set the currentTime value on the player?  We need to allow the user to select the time from which to start playing.

Thanks for any help

**Comment by SidKH** [comment]
Hi, thanks for creating an issue.

Yes, `react-azure-mp` is just a wrapper, you can do anything that is possible within Azure Media Player itself.

Setting the current time on Azure Media Player is not an easy task though.  
I found this StackOverflow comment that seems to be working https://stackoverflow.com/a/31281718/4882422

Here is an implementation with `react-azure-mp`. 
https://codesandbox.io/s/interesting-mestorf-wgv48?file=/src/index.js

Let me know if it helps.
