### ISSUE TITLE
Update React

### ISSUE THREAD

**Issue by anarmawala** [SidKH/react-azure-mp#31]
Would it be possible to update React to React 17?

**Comment by SidKH** [comment]
Hey, thanks for creating an issue.

Do you have any problems with React 17 and `react-azure-mp`?

I tried to run some examples on React 17.0.2 and it seems to work fine
https://codesandbox.io/s/wispy-haze-lvucw?file=/src/index.js

**Comment by SidKH** [comment]
I bumped up peer dependencies versions to remove warnings for React 17.

**Comment by anarmawala** [comment]
Perfect! Gonna close the issue!
